services:
  script-markup-app:
    image: ghcr.io/staljabro/script-markup-app:latest
    pull_policy: always
    container_name: script-markup-app
    ports:
      - "8086:80"
    restart: unless-stopped
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/staljabro/script-markup-app/main/public/icon.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:8087]"